apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solar-prod

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: solar-simulator
      app.kubernetes.io/part-of: solar-monitoring
    includeSelectors: false
