apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: cloudshop-prod
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'cloudshop' | base64  => Y2xvdWRzaG9w
  # echo -n 'password123' | base64 => cGFzc3dvcmQxMjM=
  # echo -n 'cloudshop' | base64  => Y2xvdWRzaG9w
  POSTGRES_USER: Y2xvdWRzaG9w
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
  POSTGRES_DB: Y2xvdWRzaG9w
