apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TysonNemeghaire1/Dev-avec-docker.git
    targetRevision: HEAD
    path: TP-Jour4/k8s/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: solar-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
